apiVersion: v2
name: ska-tmc-testing-low
description: An umbrella Helm chart for SKA-TMC-Low deployment.
type: application
version: 0.1.0
appVersion: 1.16.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
  - name: Jayant Kumbhar
    email: jayant.ska@gmail.com
  - name: Devesh Pandey
    email: devesh.ska@gmail.com
dependencies:
  - name: ska-tango-util
    version: 0.4.11
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tango-base
    version: 0.4.10
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tmc-low
    version: 0.15.1
    repository: file://../ska-tmc-low
    alias: tmc-low
  - name: ska-sdp
    version: 0.20.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-sdp.enabled
  - name: ska-csp-lmc-low
    version: 0.13.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-csp-lmc-low.enabled
  - name: ska-low-cbf
    version: 0.7.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-low-cbf.enabled
  - name: ska-low-cbf-proc
    version: 0.11.1
    repository:  https://artefact.skao.int/repository/helm-internal
    condition: ska-low-cbf.enabled
  - name: ska-low-mccs
    version: 0.14.0-dev.c944eedb3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-low-mccs.enabled
  - name: ska-ser-skuid
    version: 3.3.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-ser-skuid.enabled
  - name: ska-tango-taranta
    version: 2.8.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-tango-tangogql
    version: 1.3.10
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
