display: ":0"
xauthority: "~/.Xauthority"

legacy_compatibility: true

global:
  retry:
  - "--sleep=1"
  - "--tries=100"
  sub-system:
    ska-tango-util:
      enabled: false
    ska-tango-base:
      enabled: false
    ska-tango-taranta:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.7
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.10
      pullPolicy: IfNotPresent

ska-taranta:
  enabled: false
  ingress:
    enabled: true
    nginx: true
    hostname: k8s.stfc.skao.int
  tangogql:
    replicas: 1
    resources:
      requests:
        cpu: 600m # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem

ska-tango-base:
  enabled: true
  vnc:
    replicas: 1
    enabled: false
  tangorest:
    enabled: true
    replicas: 1
  tangodb:
    use_pv: false

# TMC-low
tmc-low:
  labels:
    app: ska-tmc-low-integration
  enabled: true
  deviceServers:
    mocks:
      enabled: true
      is_simulated:
        sdp: true
        mccs: true
        csp: true


ska-sdp:
  legacy_compatibility: true
  enabled: false
  lmc:
    prefix: low
    nsubarray: 2
  console:
    enabled: true
  data-pvc:
    create:
      enabled: true
      size: 20Gi
      storageClassName: nfss1
  ska-sdp-qa:
    kafka:
      resources:
        limits:
          cpu: 750m
          memory: 1024Mi
        requests:
          cpu: 250m
          memory: 500Mi
      livenessProbe:
        initialDelaySeconds: 30
        failureThreshold: 5
      zookeeper:
        resources:
          requests:
            cpu: 100m
  ska-tango-base:
    enabled: false

ska-low-cbf:
  enabled: false
  minikube: true
  labels:
    app: ska-csp-lmc-low
  cbf:
    hardware_connections:
      # psi-perentie1
      - 'switch=p4_01  port=19/0  speed=100  alveo=XFL14SLO1LIF'
      - 'switch=p4_01  port=21/0  speed=100  alveo=XFL1DKXBEVG2'
      - 'switch=p4_01  port=23/0  speed=100  alveo=XFL1HOOQ1Y44'
      - 'switch=p4_01  port=25/0  speed=100  alveo=XFL1LHN4TXO2'

ska-low-cbf-proc:
  deviceServers:
    processor:
      instances: ["0", "1"]
      resources:
        limits:
          xilinx.com/fpga-xilinx_u55c_gen3x16_xdma_base_3-0: 0  # no FPGA hardware
          memory: 512Mi  # reduced

ska-csp-lmc-low:
  legacy_compatibility: true
  enabled: false
  lowcsplmc:
    image:
      registry: registry.gitlab.com/ska-telescope/ska-csp-lmc-low
      image: ska-csp-lmc-low
      tag: 0.11.2
  deviceServers:
    cspcontroller:
      instances: ["controller"]
      file: "data/controller_cbf_only.yaml"
    cspsubarray:
      instances: ["subarray1", "subarray2", "subarray3", "subarray4"]
      file: "data/subarray_cbf_only.yaml"

ska-low-mccs:
  legacy_compatibility: true
  enabled: false
  deviceServers:
    controllers:
      controller:
        low-mccs/control/control:
          stationbeams:
          - low-mccs/beam/ci-1-01
          - low-mccs/beam/ci-1-02
          - low-mccs/beam/ci-1-03
          - low-mccs/beam/ci-1-04
          - low-mccs/beam/ci-1-05
          - low-mccs/beam/ci-1-06
          - low-mccs/beam/ci-1-07
          - low-mccs/beam/ci-1-08
          - low-mccs/beam/ci-1-09
          - low-mccs/beam/ci-1-10
          - low-mccs/beam/ci-1-11
          - low-mccs/beam/ci-1-12
          - low-mccs/beam/ci-1-13
          - low-mccs/beam/ci-1-14
          - low-mccs/beam/ci-1-15
          - low-mccs/beam/ci-1-16
          - low-mccs/beam/ci-1-17
          - low-mccs/beam/ci-1-18
          - low-mccs/beam/ci-1-19
          - low-mccs/beam/ci-1-20
          - low-mccs/beam/ci-1-21
          - low-mccs/beam/ci-1-22
          - low-mccs/beam/ci-1-23
          - low-mccs/beam/ci-1-24
          - low-mccs/beam/ci-1-25
          - low-mccs/beam/ci-1-26
          - low-mccs/beam/ci-1-27
          - low-mccs/beam/ci-1-28
          - low-mccs/beam/ci-1-29
          - low-mccs/beam/ci-1-30
          - low-mccs/beam/ci-1-31
          - low-mccs/beam/ci-1-32
          - low-mccs/beam/ci-1-33
          - low-mccs/beam/ci-1-34
          - low-mccs/beam/ci-1-35
          - low-mccs/beam/ci-1-36
          - low-mccs/beam/ci-1-37
          - low-mccs/beam/ci-1-38
          - low-mccs/beam/ci-1-39
          - low-mccs/beam/ci-1-40
          - low-mccs/beam/ci-1-41
          - low-mccs/beam/ci-1-42
          - low-mccs/beam/ci-1-43
          - low-mccs/beam/ci-1-44
          - low-mccs/beam/ci-1-45
          - low-mccs/beam/ci-1-46
          - low-mccs/beam/ci-1-47
          - low-mccs/beam/ci-1-48
          - low-mccs/beam/ci-2-01
          - low-mccs/beam/ci-2-02
          - low-mccs/beam/ci-2-03
          - low-mccs/beam/ci-2-04
          - low-mccs/beam/ci-2-05
          - low-mccs/beam/ci-2-06
          - low-mccs/beam/ci-2-07
          - low-mccs/beam/ci-2-08
          - low-mccs/beam/ci-2-09
          - low-mccs/beam/ci-2-10
          - low-mccs/beam/ci-2-11
          - low-mccs/beam/ci-2-12
          - low-mccs/beam/ci-2-13
          - low-mccs/beam/ci-2-14
          - low-mccs/beam/ci-2-15
          - low-mccs/beam/ci-2-16
          - low-mccs/beam/ci-2-17
          - low-mccs/beam/ci-2-18
          - low-mccs/beam/ci-2-19
          - low-mccs/beam/ci-2-20
          - low-mccs/beam/ci-2-21
          - low-mccs/beam/ci-2-22
          - low-mccs/beam/ci-2-23
          - low-mccs/beam/ci-2-24
          - low-mccs/beam/ci-2-25
          - low-mccs/beam/ci-2-26
          - low-mccs/beam/ci-2-27
          - low-mccs/beam/ci-2-28
          - low-mccs/beam/ci-2-29
          - low-mccs/beam/ci-2-30
          - low-mccs/beam/ci-2-31
          - low-mccs/beam/ci-2-32
          - low-mccs/beam/ci-2-33
          - low-mccs/beam/ci-2-34
          - low-mccs/beam/ci-2-35
          - low-mccs/beam/ci-2-36
          - low-mccs/beam/ci-2-37
          - low-mccs/beam/ci-2-38
          - low-mccs/beam/ci-2-39
          - low-mccs/beam/ci-2-40
          - low-mccs/beam/ci-2-41
          - low-mccs/beam/ci-2-42
          - low-mccs/beam/ci-2-43
          - low-mccs/beam/ci-2-44
          - low-mccs/beam/ci-2-45
          - low-mccs/beam/ci-2-46
          - low-mccs/beam/ci-2-47
          - low-mccs/beam/ci-2-48
          stations:
          - low-mccs/station/ci-1
          - low-mccs/station/ci-2
          subarraybeams:
          - low-mccs/subarraybeam/01
          - low-mccs/subarraybeam/02
          - low-mccs/subarraybeam/03
          - low-mccs/subarraybeam/04
          subarrays:
          - low-mccs/subarray/01
    stationbeams:
      stationbeams-ci-1:
        low-mccs/beam/ci-1-01:
          beam_id: 1
        low-mccs/beam/ci-1-02:
          beam_id: 2
        low-mccs/beam/ci-1-03:
          beam_id: 3
        low-mccs/beam/ci-1-04:
          beam_id: 4
        low-mccs/beam/ci-1-05:
          beam_id: 5
        low-mccs/beam/ci-1-06:
          beam_id: 6
        low-mccs/beam/ci-1-07:
          beam_id: 7
        low-mccs/beam/ci-1-08:
          beam_id: 8
        low-mccs/beam/ci-1-09:
          beam_id: 9
        low-mccs/beam/ci-1-10:
          beam_id: 10
        low-mccs/beam/ci-1-11:
          beam_id: 11
        low-mccs/beam/ci-1-12:
          beam_id: 12
        low-mccs/beam/ci-1-13:
          beam_id: 13
        low-mccs/beam/ci-1-14:
          beam_id: 14
        low-mccs/beam/ci-1-15:
          beam_id: 15
        low-mccs/beam/ci-1-16:
          beam_id: 16
        low-mccs/beam/ci-1-17:
          beam_id: 17
        low-mccs/beam/ci-1-18:
          beam_id: 18
        low-mccs/beam/ci-1-19:
          beam_id: 19
        low-mccs/beam/ci-1-20:
          beam_id: 20
        low-mccs/beam/ci-1-21:
          beam_id: 21
        low-mccs/beam/ci-1-22:
          beam_id: 22
        low-mccs/beam/ci-1-23:
          beam_id: 23
        low-mccs/beam/ci-1-24:
          beam_id: 24
        low-mccs/beam/ci-1-25:
          beam_id: 25
        low-mccs/beam/ci-1-26:
          beam_id: 26
        low-mccs/beam/ci-1-27:
          beam_id: 27
        low-mccs/beam/ci-1-28:
          beam_id: 28
        low-mccs/beam/ci-1-29:
          beam_id: 29
        low-mccs/beam/ci-1-30:
          beam_id: 30
        low-mccs/beam/ci-1-31:
          beam_id: 31
        low-mccs/beam/ci-1-32:
          beam_id: 32
        low-mccs/beam/ci-1-33:
          beam_id: 33
        low-mccs/beam/ci-1-34:
          beam_id: 34
        low-mccs/beam/ci-1-35:
          beam_id: 35
        low-mccs/beam/ci-1-36:
          beam_id: 36
        low-mccs/beam/ci-1-37:
          beam_id: 37
        low-mccs/beam/ci-1-38:
          beam_id: 38
        low-mccs/beam/ci-1-39:
          beam_id: 39
        low-mccs/beam/ci-1-40:
          beam_id: 40
        low-mccs/beam/ci-1-41:
          beam_id: 41
        low-mccs/beam/ci-1-42:
          beam_id: 42
        low-mccs/beam/ci-1-43:
          beam_id: 43
        low-mccs/beam/ci-1-44:
          beam_id: 44
        low-mccs/beam/ci-1-45:
          beam_id: 45
        low-mccs/beam/ci-1-46:
          beam_id: 46
        low-mccs/beam/ci-1-47:
          beam_id: 47
        low-mccs/beam/ci-1-48:
          beam_id: 48
      stationbeams-ci-2:
        low-mccs/beam/ci-2-01:
          beam_id: 49
        low-mccs/beam/ci-2-02:
          beam_id: 50
        low-mccs/beam/ci-2-03:
          beam_id: 51
        low-mccs/beam/ci-2-04:
          beam_id: 52
        low-mccs/beam/ci-2-05:
          beam_id: 53
        low-mccs/beam/ci-2-06:
          beam_id: 54
        low-mccs/beam/ci-2-07:
          beam_id: 55
        low-mccs/beam/ci-2-08:
          beam_id: 56
        low-mccs/beam/ci-2-09:
          beam_id: 57
        low-mccs/beam/ci-2-10:
          beam_id: 58
        low-mccs/beam/ci-2-11:
          beam_id: 59
        low-mccs/beam/ci-2-12:
          beam_id: 60
        low-mccs/beam/ci-2-13:
          beam_id: 61
        low-mccs/beam/ci-2-14:
          beam_id: 62
        low-mccs/beam/ci-2-15:
          beam_id: 63
        low-mccs/beam/ci-2-16:
          beam_id: 64
        low-mccs/beam/ci-2-17:
          beam_id: 65
        low-mccs/beam/ci-2-18:
          beam_id: 66
        low-mccs/beam/ci-2-19:
          beam_id: 67
        low-mccs/beam/ci-2-20:
          beam_id: 68
        low-mccs/beam/ci-2-21:
          beam_id: 69
        low-mccs/beam/ci-2-22:
          beam_id: 70
        low-mccs/beam/ci-2-23:
          beam_id: 71
        low-mccs/beam/ci-2-24:
          beam_id: 72
        low-mccs/beam/ci-2-25:
          beam_id: 73
        low-mccs/beam/ci-2-26:
          beam_id: 74
        low-mccs/beam/ci-2-27:
          beam_id: 75
        low-mccs/beam/ci-2-28:
          beam_id: 76
        low-mccs/beam/ci-2-29:
          beam_id: 77
        low-mccs/beam/ci-2-30:
          beam_id: 78
        low-mccs/beam/ci-2-31:
          beam_id: 79
        low-mccs/beam/ci-2-32:
          beam_id: 80
        low-mccs/beam/ci-2-33:
          beam_id: 81
        low-mccs/beam/ci-2-34:
          beam_id: 82
        low-mccs/beam/ci-2-35:
          beam_id: 83
        low-mccs/beam/ci-2-36:
          beam_id: 84
        low-mccs/beam/ci-2-37:
          beam_id: 85
        low-mccs/beam/ci-2-38:
          beam_id: 86
        low-mccs/beam/ci-2-39:
          beam_id: 87
        low-mccs/beam/ci-2-40:
          beam_id: 88
        low-mccs/beam/ci-2-41:
          beam_id: 89
        low-mccs/beam/ci-2-42:
          beam_id: 90
        low-mccs/beam/ci-2-43:
          beam_id: 91
        low-mccs/beam/ci-2-44:
          beam_id: 92
        low-mccs/beam/ci-2-45:
          beam_id: 93
        low-mccs/beam/ci-2-46:
          beam_id: 94
        low-mccs/beam/ci-2-47:
          beam_id: 95
        low-mccs/beam/ci-2-48:
          beam_id: 96
    stations:
      station-ci-1:
        low-mccs/station/ci-1:
          antenna_trls: []
          field_station_trl: ""
          logging_level_default: 5
          sps_station_trl: ""
          station_calibrator_trl: ""
          station_id: 1
      station-ci-2:
        low-mccs/station/ci-2:
          antenna_trls: []
          field_station_trl: ""
          logging_level_default: 5
          sps_station_trl: ""
          station_calibrator_trl: ""
          station_id: 2
    subarraybeams:
      subarraybeam-01:
        low-mccs/subarraybeam/01:
          logging_level_default: 5
      subarraybeam-02:
        low-mccs/subarraybeam/02:
          logging_level_default: 5
      subarraybeam-03:
        low-mccs/subarraybeam/03:
          logging_level_default: 5
      subarraybeam-04:
        low-mccs/subarraybeam/04:
          logging_level_default: 5
    subarrays:
      subarray-01:
        low-mccs/subarray/01:
          logging_level_default: 5
          skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
          subarray_id: 1
  global:
    cluster_domain: cluster.local
    minikube: true
    tango_host: databaseds-tango-base:10000


# SKUID
ska-ser-skuid:
  labels:
    app: ska-tmc-low-integration
  enabled: true
  skuid:
    use_pv: false
    config:
      generator_id: mvp01
