display: ":0"
xauthority: "~/.Xauthority"

legacy_compatibility: true

global:
  retry: 
  - "--sleep=1"
  - "--tries=100"
  sub-system:
    ska-tango-util:
      enabled: false
    ska-tango-base:
      enabled: false
    ska-tango-taranta:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.7
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.10
      pullPolicy: IfNotPresent

ska-taranta:
  enabled: false
  ingress:
    enabled: true
    nginx: true
    hostname: k8s.stfc.skao.int
  tangogql:
    replicas: 1
    resources:
      requests:
        cpu: 600m # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem

ska-tango-base:
  enabled: true
  vnc:
    replicas: 1
    enabled: false
  tangorest:
    enabled: true
    replicas: 1
  tangodb:
    use_pv: false

# TMC-low
tmc-low:
  labels:
    app: ska-tmc-low-integration
  enabled: true
  deviceServers:
    mocks:
      enabled: true
      is_simulated:
        sdp: true

 
ska-sdp:
  legacy_compatibility: true
  enabled: false
  lmc:
    prefix: low
    nsubarray: 2
  console:
    enabled: true
  data-pvc:
    create:
      enabled: true
      size: 20Gi
      storageClassName: nfss1
  ska-sdp-qa:
    kafka:
      resources:
        limits:
          cpu: 750m
          memory: 1024Mi
        requests:
          cpu: 250m
          memory: 500Mi
      livenessProbe:
        initialDelaySeconds: 30
        failureThreshold: 5
      zookeeper:
        resources:
          requests:
            cpu: 100m
  ska-tango-base:
    enabled: false

ska-low-cbf:
  enabled: false
  minikube: true
  ska-low-cbf-conn:
    enabled: false
  ska-low-cbf-proc:
    enabled: false
    deviceServers:
      processor:
        instances: ["0","1","2"]  # 2x CNIC, 1x SUT
        # TODO - check if the resources section is needed - in principle, it should be set in -proc chart
        resources:
          limits:
            xilinx.com/fpga-xilinx_u55c_gen3x16_xdma_base_3-0: 0  # no FPGA hardware
            memory: 512Mi  # reduced

ska-csp-lmc-low:
  legacy_compatibility: true
  enabled: false
  deviceServers:
    cspcontroller:
      instances: ["controller"]
      file: "data/controller_cbf_only.yaml"
    cspsubarray:
      instances: ["subarray1", "subarray2", "subarray3", "subarray4"]
      file: "data/subarray_cbf_only.yaml"

# SKUID
ska-ser-skuid:
  labels:
    app: ska-tmc-low-integration
  enabled: true
  skuid:
    use_pv: false
    config:
      generator_id: mvp01