display: ":0"
xauthority: "~/.Xauthority"

legacy_compatibility: true

global:
  retry:
  - "--sleep=1"
  - "--tries=100"
  sub-system:
    ska-tango-util:
      enabled: false
    ska-tango-base:
      enabled: false
    ska-tango-taranta:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.7
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.10
      pullPolicy: IfNotPresent
  cluster_domain: cluster.local

ska-tango-tangogql:
  ska-tango-base:
    enabled: false

  ska-tango-examples:
    enabled: false
  replicas: 1
  resources:
    requests:
      cpu: 200m # 200m = 0.2 CPU
      memory: 200Mi # 200Mi = 0.2 GB mem
    limits:
      memory: 1024Mi # 1024Mi = 1 GB mem


ska-tango-base:
  enabled: true
  vnc:
    replicas: 1
    enabled: false
  tangorest:
    enabled: true
    replicas: 1
  tangodb:
    use_pv: false

# TMC-low
tmc-low:
  labels:
    app: ska-tmc-low-integration
  enabled: true
  deviceServers:
    mocks:
      enabled: true
      is_simulated:
        sdp: true
        mccs: true
        csp: true

ska-sdp:
  legacy_compatibility: true
  enabled: false
  lmc:
    prefix: low
    nsubarray: 1
  console:
    enabled: true
  data-pvc:
    create:
      enabled: true
      size: 100Mi
      storageClassName: nfss1
  ska-sdp-qa:
    kafka:
      resources:
        limits:
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 50Mi
      livenessProbe:
        initialDelaySeconds: 30
        failureThreshold: 5
      zookeeper:
        resources:
          requests:
            cpu: 100m
  ska-tango-base:
    enabled: false


ska-low-cbf:
  labels:
    app: ska-tmc-low-integration
  enabled: false
  minikube: true
  cbf:
    hardware_connections:
      # psi-perentie1
      - 'switch=p4_01  port=19/0  speed=100  alveo=XFL14SLO1LIF'
      - 'switch=p4_01  port=21/0  speed=100  alveo=XFL1DKXBEVG2'
      - 'switch=p4_01  port=23/0  speed=100  alveo=XFL1HOOQ1Y44'
      - 'switch=p4_01  port=25/0  speed=100  alveo=XFL1LHN4TXO2'

ska-low-cbf-proc:
  labels:
    app: ska-tmc-low-integration
  deviceServers:
    processor:
      instances: ["0", "1"]
      resources:
        requests:
          memory: 100Mi
        limits:
          amd.com/xilinx_u55c_gen3x16_xdma_base_3-0: 0  # no FPGA hardware
          memory: 300Mi  # reduced

ska-csp-lmc-low:
  labels:
    app: ska-tmc-low-integration
  legacy_compatibility: true
  enabled: false
  deviceServers:
    cspcontroller:
      instances: ["controller"]
      file: "data/controller_cbf_only.yaml"
    cspsubarray:
      instances: ["subarray1", "subarray2", "subarray3", "subarray4"]
      file: "data/subarray_cbf_only.yaml"

ska-pst:
  labels:
    app: ska-tmc-low-integration
  enabled: false
  ska-pst-core:
    enabled: false
    serviceAccount:
      create: false
    send:
      enabled: true
      dpdApiIntegration: true
  ska-pst-jupyterlab:
    enabled: false
  ska-pst-lmc:
    enabled: true
    beam:
      simulationMode: 1
      scanOutputDirPattern: /tmp/<eb_id>/<subsystem_id>/<scan_id>
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: []
  volume: null

ska-low-mccs:
  labels:
    app: ska-tmc-low-integration
  legacy_compatibility: true
  enabled: false
  daqDataRepository: daq-data
  deviceServers:
    antennas:
      antennas-ci-1:
        low-mccs/antenna/ci-1-sb01-01:
          antenna_id: 244
          field_station_trl: low-mccs/fieldstation/ci-1
          logging_level_default: 5
          tile_trl: low-mccs/tile/ci-1-tpm01
          tile_x_channel: 31
          tile_y_channel: 30
          x_displacement: -5.422
          y_displacement: 17.79
          z_displacement: 0.008
      antennas-ci-2:
        low-mccs/antenna/ci-2-sb01-01:
          antenna_id: 244
          field_station_trl: low-mccs/fieldstation/ci-2
          logging_level_default: 5
          tile_trl: low-mccs/tile/ci-2-tpm01
          tile_x_channel: 31
          tile_y_channel: 30
          x_displacement: -5.422
          y_displacement: 17.79
          z_displacement: 0.008
    cabinetbanks:
      cabinetbank-cb-1:
        low-mccs/cabinetbank/cb-1:
          cabinetbank_id: 1
          stations:
          - low-mccs/station/ci-1
          - low-mccs/station/ci-2
    calibrationstores:
      ci-1:
        low-mccs/calibrationstore/ci-1:
          logging_level_default: 5
      ci-2:
        low-mccs/calibrationstore/ci-2:
          logging_level_default: 5
    controllers:
      controller:
        low-mccs/control/control:
          cabinetbanks:
          - low-mccs/cabinetbank/cb-1
          stationbeams:
          - low-mccs/beam/ci-1-01
          - low-mccs/beam/ci-1-02
          stations:
          - low-mccs/station/ci-1
          - low-mccs/station/ci-2
          subarraybeams:
          - low-mccs/subarraybeam/01
          - low-mccs/subarraybeam/02
          subarrays:
          - low-mccs/subarray/01
    solvers:
      ci-1:
        low-mccs/solver/ci-1:
          eep_root_path: /app/tests/unit/calibration_solver/testing_data
          logging_level_default: 5
          root_path: /app/tests/unit/calibration_solver/testing_data
      ci-2:
        low-mccs/solver/ci-2:
          eep_root_path: /eep-data
          logging_level_default: 5
          root_path: /daq-data
    stationbeams:
      stationbeams-ci-1:
        low-mccs/beam/ci-1-01:
          beam_id: 1
      stationbeams-ci-2:
        low-mccs/beam/ci-2-01:
          beam_id: 49
    stationcalibrators:
      ci-1:
        low-mccs/stationcalibrator/ci-1:
          calibration_solver_trl: low-mccs/solver/solver-ci-1
          calibration_store_trl: low-mccs/calibrationstore/ci-1
          logging_level_default: 5
          station_trl: low-mccs/station/ci-1
      ci-2:
        low-mccs/stationcalibrator/ci-2:
          calibration_solver_trl: low-mccs/solver/solver-ci-2
          calibration_store_trl: low-mccs/calibrationstore/ci-2
          logging_level_default: 5
          station_trl: low-mccs/station/ci-2
    stations:
      station-ci-1:
        low-mccs/station/ci-1:
          antenna_ids:
          - 244
          - 189
          antenna_trls:
          - low-mccs/antenna/ci-1-sb01-01
          - low-mccs/antenna/ci-1-sb01-02
          antenna_xs:
          - -5.422
          - -3.975
          antenna_ys:
          - 17.79
          - 15.948
          antenna_zs:
          - 0.008
          - 0.016
          field_station_trl: low-mccs/fieldstation/ci-1
          logging_level_default: 5
          ref_height: 1
          ref_latitude: -1
          ref_longitude: 1
          sps_station_trl: low-mccs/spsstation/ci-1
          station_calibrator_trl: low-mccs/stationcalibrator/ci-1
          station_id: 1
      station-ci-2:
        low-mccs/station/ci-2:
          antenna_ids:
          - 244
          - 189
          antenna_trls:
          - low-mccs/antenna/ci-2-sb01-01
          - low-mccs/antenna/ci-2-sb01-02
          antenna_xs:
          - -5.422
          - -3.975
          antenna_ys:
          - 17.79
          - 15.948
          antenna_zs:
          - 0.008
          - 0.016
          field_station_trl: low-mccs/fieldstation/ci-2
          logging_level_default: 5
          ref_height: 0
          ref_latitude: 0
          ref_longitude: 0
          sps_station_trl: low-mccs/spsstation/ci-2
          station_calibrator_trl: low-mccs/stationcalibrator/ci-2
          station_id: 2
    subarraybeams:
      subarraybeam-01:
        low-mccs/subarraybeam/01:
          logging_level_default: 5
      subarraybeam-02:
        low-mccs/subarraybeam/02:
          logging_level_default: 5
      subarraybeam-03:
        low-mccs/subarraybeam/03:
          logging_level_default: 5
      subarraybeam-04:
        low-mccs/subarraybeam/04:
          logging_level_default: 5
    subarrays:
      subarray-01:
        low-mccs/subarray/01:
          logging_level_default: 5
          skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
          subarray_id: 1
  global:
    cluster_domain: techops.internal.skao.int
    minikube: true
    tango_host: databaseds-tango-base:10000
  ska-low-mccs-pasd:
    configServers:
      array:
        host: pasd-configuration-service
        port: 8081
    deviceServers:
      fieldstations:
        ci-1:
          low-mccs/fieldstation/ci-1:
            configuration_host: pasd-configuration-service
            configuration_port: 8081
            fndh_name: low-mccs/fndh/ci-1
            logging_level_default: 5
            smartbox_names:
            - low-mccs/smartbox/ci-1-sb01
        ci-2:
          low-mccs/fieldstation/ci-2:
            configuration_host: pasd-configuration-service
            configuration_port: 8081
            fndh_name: low-mccs/fndh/ci-2
            logging_level_default: 5
            smartbox_names:
            - low-mccs/smartbox/ci-2-sb01
      fndhs:
        ci-1:
          low-mccs/fndh/ci-1:
            logging_level_default: 5
            pasdbus_name: low-mccs/pasdbus/ci-1
        ci-2:
          low-mccs/fndh/ci-2:
            logging_level_default: 5
            pasdbus_name: low-mccs/pasdbus/ci-2
      pasdbuses:
        ci-1:
          low-mccs/pasdbus/ci-1:
            device_polling_rate: 3
            host: pasd-simulator-ci-1
            logging_level_default: 5
            polling_rate: 0.2
            port: 9502
            simulation_config: 1
            timeout: 10
        ci-2:
          low-mccs/pasdbus/ci-2:
            device_polling_rate: 3
            host: pasd-simulator-ci-2
            logging_level_default: 5
            polling_rate: 0.2
            port: 9502
            simulation_config: 1
            timeout: 10
      smartboxes:
        ci-1-sb01:
          low-mccs/smartbox/ci-1-sb01:
            field_station_name: low-mccs/fieldstation/ci-1
            fndh_name: low-mccs/fndh/ci-1
            fndh_port: 1
            logging_level_default: 5
            pasdbus_name: low-mccs/pasdbus/ci-1
            smartbox_number: 1
        ci-2-sb01:
          low-mccs/smartbox/ci-2-sb01:
            field_station_name: low-mccs/fieldstation/ci-2
            fndh_name: low-mccs/fndh/ci-2
            fndh_port: 1
            logging_level_default: 5
            pasdbus_name: low-mccs/pasdbus/ci-2
            smartbox_number: 1
    referenceData:
      pasdconfiguration:
        ci-1:
          antennas:
            sb01-01:
              masked: false
              smartbox: sb01
              smartbox_port: 1
          pasd:
            smartboxes:
              sb01:
                fndh_port: 1
        ci-2:
          antennas:
            sb01-01:
              masked: false
              smartbox: sb01
              smartbox_port: 1
          pasd:
            smartboxes:
              sb01:
                fndh_port: 1
    simulators:
      pasdbuses:
        ci-1:
          host: pasd-simulator-ci-1
          port: 9502
  ska-low-mccs-spshw:
    deviceServers:
      daqs:
        bandpass-daq-ci-1:
          low-mccs/bandpass-daq/ci-1:
            host: daqrx-ci-1-bandpass
            id: 1
            logging_level_default: 5
            port: 50051
            skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
        bandpass-daq-ci-2:
          low-mccs/bandpass-daq/ci-2:
            host: daqrx-ci-2-bandpass
            id: 2
            logging_level_default: 5
            port: 50051
            skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
        calibration-daq-ci-1:
          low-mccs/calibration-daq/ci-1:
            host: daqrx-ci-1-calibration
            id: 1
            logging_level_default: 5
            port: 50051
            skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
        calibration-daq-ci-2:
          low-mccs/calibration-daq/ci-2:
            host: daqrx-ci-2-calibration
            id: 2
            logging_level_default: 5
            port: 50051
            skuid_url: http://ska-ser-skuid-ska-ser-skuid-svc:9870/
      spsstations:
        ci-1:
          low-mccs/spsstation/ci-1:
            antenna_config_uri: []
            daq_trl: low-mccs/calibration-daq/ci-1
            logging_level_default: 5
            sdn_first_interface: 10.0.0.128/16
            station_id: 1
            subracks:
            - low-mccs/subrack/ci-1-sr1
            tpms:
            - low-mccs/tile/ci-1-tpm01
        ci-2:
          low-mccs/spsstation/ci-2:
            antenna_config_uri: []
            daq_trl: low-mccs/calibration-daq/ci-2
            logging_level_default: 5
            sdn_first_interface: 10.0.0.192/16
            station_id: 2
            subracks:
            - low-mccs/subrack/ci-2-sr1
            tpms:
            - low-mccs/tile/ci-2-tpm01
      subracks:
        ci-1-sr1:
          low-mccs/subrack/ci-1-sr1:
            logging_level_default: 5
            srmb_host: subrack-simulator-ci-1-sr1
            srmb_port: 8081
        ci-2-sr1:
          low-mccs/subrack/ci-2-sr1:
            logging_level_default: 5
            srmb_host: subrack-simulator-ci-2-sr1
            srmb_port: 8081
      tpms:
        ci-1-tpm01:
          low-mccs/tile/ci-1-tpm01:
            host: 10.0.10.201
            logging_level_default: 5
            port: 10000
            simulation_config: 1
            station_id: 1
            subrack: ci-1-sr1
            subrack_slot: 1
            test_config: 1
            tile_id: 0
            version: tpm_v1_6
        ci-2-tpm01:
          low-mccs/tile/ci-2-tpm01:
            host: 10.0.10.201
            logging_level_default: 5
            port: 10000
            simulation_config: 1
            station_id: 2
            subrack: ci-2-sr1
            subrack_slot: 1
            test_config: 1
            tile_id: 0
            version: tpm_v1_6
    simulators:
      subracks:
        ci-1-sr1:
          srmb_host: subrack-simulator-ci-1-sr1
          srmb_port: 8081
    ska-low-mccs-daq:
      receivers:
        ci-1-bandpass:
          affinity: null
          expose_data_service: true
          grpc_port: 50051
          node_selector: null
          nvidia_gpu: false
          receiver_interface: eth0
          receiver_port: 4660
          tolerations: null
        ci-2-bandpass:
          affinity: null
          expose_data_service: true
          grpc_port: 50051
          node_selector: null
          nvidia_gpu: false
          receiver_interface: eth0
          receiver_port: 4660
          tolerations: null
        ci-1-calibration:
          affinity: null
          expose_data_service: true
          grpc_port: 50051
          node_selector: null
          nvidia_gpu: false
          receiver_interface: eth0
          receiver_port: 4660
          tolerations: null
        ci-2-calibration:
          affinity: null
          expose_data_service: true
          grpc_port: 50051
          node_selector: null
          nvidia_gpu: false
          receiver_interface: eth0
          receiver_port: 4660
          tolerations: null
      storage:
        daq-data:
          size: 250Mi
          storage_class: nfss1
      
# SKUID
ska-ser-skuid:
  labels:
    app: ska-tmc-low-integration
  enabled: true
  skuid:
    use_pv: false
    config:
      generator_id: mvp01