apiVersion: v2
name: ska-tmc-template
description: A subchart for ska-tmc-template deployment.
type: application
version: 0.0.1
appVersion: 0.0.1
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
  - name: Jayant Kumbhar
    email: jayant.ska@gmail.com
  - name: Devesh Pandey
    email: devesh.ska@gmail.com

